import type { BlogTemplate } from "./types";

export const BLOG_TEMPLATES: { key: BlogTemplate; name: string; description: string; html: string }[] = [
  { key: "editorial", name: "Editorial story", description: "A clean article with a lead, sections and a closing note.", html: `<p><strong>In brief:</strong> Write a short opening that tells readers what this article covers and why it matters.</p>\n<h2>What you need to know</h2>\n<p>Add the main context and explain the important details in plain language.</p>\n<h2>Key details</h2>\n<ul>\n  <li>First important point</li>\n  <li>Second important point</li>\n  <li>Who this information is for</li>\n</ul>\n<h2>What to do next</h2>\n<p>Give readers a clear next step and link to the official source where relevant.</p>\n<blockquote>Always verify dates and requirements with the official notification.</blockquote>` },
  { key: "guide", name: "Step-by-step guide", description: "Numbered sections for explainers, applications and exam preparation.", html: `<p>Use this introduction to describe the goal of the guide and who should follow it.</p>\n<h2>Before you begin</h2>\n<ul>\n  <li>Keep the required documents ready</li>\n  <li>Check the official dates and eligibility rules</li>\n</ul>\n<h2>Step 1: Read the official instructions</h2>\n<p>Explain the first action readers should take.</p>\n<h2>Step 2: Prepare your information</h2>\n<p>Describe the details or documents readers need to collect.</p>\n<h2>Step 3: Complete the process</h2>\n<p>Walk through the remaining steps and mention common mistakes to avoid.</p>\n<h2>Checklist</h2>\n<ol>\n  <li>Confirm eligibility</li>\n  <li>Review every field before submitting</li>\n  <li>Save the confirmation for your records</li>\n</ol>` },
  { key: "announcement", name: "News announcement", description: "A prominent notice with a summary, dates and official links.", html: `<p><strong>Announcement:</strong> Summarize the update in one or two sentences.</p>\n<h2>Important dates</h2>\n<ul>\n  <li><strong>Notification:</strong> Add date</li>\n  <li><strong>Applications open:</strong> Add date</li>\n  <li><strong>Last date:</strong> Add date</li>\n</ul>\n<h2>Who should read this?</h2>\n<p>Explain which candidates or readers are affected by this announcement.</p>\n<h2>Official information</h2>\n<p>Summarize the main details and include a link to the issuing authority's notice.</p>\n<p><strong>Reminder:</strong> Check the official source for changes before acting.</p>` },
];

export function getBlogTemplate(key: BlogTemplate) {
  return BLOG_TEMPLATES.find((template) => template.key === key) ?? BLOG_TEMPLATES[0];
}
