import { AUTH_ENDPOINT } from ".";
import { SP_NAME } from "./spName";

export const API_ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  GET_FRANCHISE_LOGO_AND_NAME: `/execute-sp/auth-all/SpUsers/2`,

  RESET_USER_DEVICE: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_USERS}/3`,
  // IS_ACTIVE_TOGGLE_USER: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_USERS}/4`,

  GET_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/1`,
  UPSERT_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/2`,

  GET_STUDENT_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/1`,
  UPSERT_STUDENT_DETAILS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/2`,
  GET_STUDENT_DETAILS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/3`,
  REGISTER_STUDENT: "/auth/register-student",

  GET_CATEGORY_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/1`,
  UPSERT_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/2`,
  DELETE_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/3`,
  GET_CATEGORY_PARENT_CHILD_BY_ID: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/4`,
  GET_PARENT_CATEGORY_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/5`,
  GET_ASSIGNED_FRANCHISE_CATEGORIES: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/6`,
  GET_CATEGORIES_WITH_QUESTION_COUNTS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/8`,

  UPSERT_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/1`,
  GET_QUESTION_ANS_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/2`,
  DELETE_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/3`,
  GET_QUESTION_ANS_BY_ID: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/4`,
  GET_FILTERED_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/5`,
  BULK_UPSERT_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/6`,

  GET_TEST_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/1`,
  UPSERT_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/2`,
  DELETE_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/3`,
  GET_TEST_BY_ID: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/4`,
  GET_FULL_TEST_DETAILS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/5`,
  TOGGLE_BOOKMARK: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/6`,
  CREATE_CUSTOM_PRACTICE: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/8`,

  UPSERT_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST_QUESTIONS}/1`,
  GET_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST_QUESTIONS}/2`,

  GET_FRANCHISE_DROP_DOWN: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/SpCommonDropDownList/1`,
  GET_FRANCHISE_TEST_MAPPINGS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/SpCommonDropDownList/2`,
  SAVE_FRANCHISE_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/7`,

  GET_DISPLAY_VIEW_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/1`,
  GET_DISPLAY_VIEW_LIST_FOR_STUDENT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/7`,
  UPSERT_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/2`,
  DELETE_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/3`,
  GET_DISPLAY_VIEW_CHILDREN: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/4`,
  GET_DISPLAY_VIEW_STUDENT_LIST:  `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/5`,
  ASSIGN_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/6`,

  // DisplayViewTest — assign tests to display view nodes
  UPSERT_DISPLAY_VIEW_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/1`,
  DELETE_DISPLAY_VIEW_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/2`,
  GET_DISPLAY_VIEW_TESTS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/3`,

  // DisplayViewStudyMaterial
  UPSERT_DISPLAY_VIEW_STUDY_MATERIAL: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_STUDY_MATERIAL}/1`,
  DELETE_DISPLAY_VIEW_STUDY_MATERIAL: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_STUDY_MATERIAL}/2`,
  GET_DISPLAY_VIEW_STUDY_MATERIAL: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW_STUDY_MATERIAL}/3`,

  // Practice Attempts — accessible by all authenticated users
  // Backend SP: SpAttempt
  // Payload for START_ATTEMPT:   { test_id: number }
  // Returns:                     { id, student_id, test_id, score, started_at }
  // Payload for SUBMIT_ATTEMPT:  { attempt_id: number, answers: [{ question_id, selected_option_id }] }
  // Returns:                     { attempt_id, score, total_questions, correct_answers }
  START_ATTEMPT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/1`,
  SUBMIT_ATTEMPT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/2`,
  GET_ATTEMPT_REVIEW: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/3`,
  GET_ATTEMPT_HISTORY: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/4`,

  // Student Category Assignment
  GET_STUDENT_CATEGORIES: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT_CATEGORIES}/1`,
  TOGGLE_STUDENT_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT_CATEGORIES}/2`,
  GET_LEADERBOARD: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_LEADERBOARD}/1`,

  // Study Material
  GET_STUDY_MATERIAL_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_STUDY_MATERIAL}/3`,
  UPSERT_STUDY_MATERIAL: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDY_MATERIAL}/1`,
  DELETE_STUDY_MATERIAL: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDY_MATERIAL}/2`,

  // Student Content (Notes & Videos)
  GET_STUDENT_CONTENT_ROOTS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_STUDENT_STUDY_MATERIAL}/1`,
  GET_STUDENT_CONTENT_TREE: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_STUDENT_STUDY_MATERIAL}/2`,
  GET_STUDENT_CONTENT_FLAT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_STUDENT_STUDY_MATERIAL}/3`,
  // Franchise Category Assignment
  GET_FRANCHISE_CATEGORIES: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE_CATEGORIES}/1`,
  TOGGLE_FRANCHISE_CATEGORY: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE_CATEGORIES}/2`,

  // Dashboard Metrics
  GET_ADMIN_DASHBOARD_STATS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DASHBOARD}/1`,
  GET_STUDENT_DASHBOARD_STATS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DASHBOARD}/2`,

  // Fees Management
  GET_FEES_DASHBOARD: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/1`,
  GET_STUDENT_FEES_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/2`,
  RECORD_FEE_PAYMENT: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/3`,
  GET_FEE_STRUCTURES: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/4`,
  UPSERT_FEE_STRUCTURE: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/5`,
  ASSIGN_FEE_STRUCTURE: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/6`,
  GET_PAYMENT_RECEIPT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_FEES}/7`,
  GET_MY_STUDENT_FEES: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_FEES}/8`,
  GET_PAYMENT_REPORTS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_FEES}/9`,

  // Student Full Details SP
  GET_STUDENT_COMPLETE_DETAILS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT_DETAILS}/1`,

  // Job management (super-admin only)
  GET_JOBS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/1`,
  UPSERT_JOB: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/2`,
  CLOSE_JOB: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/3`,
  GET_JOB_CATEGORIES: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/4`,
  CREATE_JOB_CATEGORY: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/7`,
  GET_JOB_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_JOBS}/8`,

  // Blog management (super-admin only)
  GET_BLOGS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_BLOGS}/1`,
  UPSERT_BLOG: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_BLOGS}/2`,
  SET_BLOG_STATUS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_BLOGS}/3`,
  GET_BLOG_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_BLOGS}/4`,

  // Daily current affairs management (super-admin only)
  GET_DAILY_CURRENT_AFFAIRS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_DAILY_CURRENT_AFFAIRS}/1`,
  UPSERT_DAILY_CURRENT_AFFAIRS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_DAILY_CURRENT_AFFAIRS}/2`,
  SET_DAILY_CURRENT_AFFAIRS_STATUS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_DAILY_CURRENT_AFFAIRS}/3`,
  GET_DAILY_CURRENT_AFFAIRS_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_DAILY_CURRENT_AFFAIRS}/4`,

  // FAQ management (super-admin only)
  GET_FAQS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FAQS}/1`,
  UPSERT_FAQ: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FAQS}/2`,
  DELETE_FAQ: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FAQS}/3`,
  GET_FAQ_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FAQS}/4`,
  TOGGLE_FAQ_STATUS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FAQS}/5`,

  // Testimonials management (super-admin only)
  GET_TESTIMONIALS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_TESTIMONIALS}/1`,
  UPSERT_TESTIMONIAL: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_TESTIMONIALS}/2`,
  DELETE_TESTIMONIAL: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_TESTIMONIALS}/3`,
  GET_TESTIMONIAL_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_TESTIMONIALS}/4`,
  TOGGLE_TESTIMONIAL_STATUS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_TESTIMONIALS}/5`,

  // Contact inquiries management (super-admin only)
  GET_CONTACT_SUBMISSIONS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_CONTACT_US}/1`,
  DELETE_CONTACT_SUBMISSION: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_CONTACT_US}/3`,
  GET_CONTACT_SUBMISSION_BY_ID: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_CONTACT_US}/4`,
  TOGGLE_CONTACT_READ_STATUS: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_CONTACT_US}/5`,
};
