CREATE TABLE [dbo].[franchises] (
    [id]               INT            IDENTITY (1, 1) NOT NULL,
    [name]             NVARCHAR (255) NOT NULL,
    [code]             NVARCHAR (50)  NOT NULL,
    [owner_name]       NVARCHAR (255) NULL,
    [contact_email]    NVARCHAR (255) NULL,
    [status]           BIT            DEFAULT ((1)) NULL,
    [created_at]       DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [contact_phone]    NVARCHAR (20)  NULL,
    [alternate_phone]  NVARCHAR (20)  NULL,
    [website_url]      NVARCHAR (500) NULL,
    [address_line1]    NVARCHAR (255) NULL,
    [address_line2]    NVARCHAR (255) NULL,
    [city]             NVARCHAR (100) NULL,
    [state]            NVARCHAR (100) NULL,
    [country]          NVARCHAR (100) NULL,
    [postal_code]      NVARCHAR (20)  NULL,
    [logo_url]         NVARCHAR (500) NULL,
    [smtp_host]        NVARCHAR (255) NULL,
    [smtp_port]        INT            NULL,
    [smtp_email]       NVARCHAR (255) NULL,
    [smtp_password]    NVARCHAR (500) NULL,
    [smtp_enable_ssl]  BIT            DEFAULT ((1)) NOT NULL,
    [smtp_sender_name] NVARCHAR (255) NULL,
    [pan_number]       NVARCHAR (100) NULL,
    [gst_number]       NVARCHAR (20)  NULL,
    [logo_document_Id] INT            NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    UNIQUE NONCLUSTERED ([code] ASC)
);

