import type { CurrentAffairsTemplate } from "./types";

export const CURRENT_AFFAIRS_TEMPLATES: { key: CurrentAffairsTemplate; name: string; description: string; html: string }[] = [
  { key: "daily-brief", name: "Daily brief", description: "Short summary, key facts and exam takeaway.", html: `<p><strong>In brief:</strong> Summarize the update in two or three clear sentences.</p>\n<h2>What happened?</h2>\n<p>Describe the development, announcement or event. Include the relevant date and organizations.</p>\n<h2>Key facts</h2>\n<ul>\n  <li><strong>Organization:</strong> Add the name</li>\n  <li><strong>Location or scope:</strong> Add the details</li>\n  <li><strong>Why it matters:</strong> Explain the significance</li>\n</ul>\n<h2>Exam takeaway</h2>\n<p>Connect this update to a subject or concept that candidates should revise.</p>\n<p><em>Refer to the linked official source for the latest details.</em></p>` },
  { key: "topic-explainer", name: "Topic explainer", description: "Context, background and the wider significance of a topic.", html: `<p>Introduce the topic and explain the current development that brought it into focus.</p>\n<h2>Background</h2>\n<p>Add essential context so readers can understand the issue.</p>\n<h2>Recent development</h2>\n<p>Summarize the latest verified update and identify the organizations involved.</p>\n<h2>Why it matters</h2>\n<ul>\n  <li>Explain the impact on people, policy or the economy.</li>\n  <li>Connect the issue to the relevant examination subject.</li>\n</ul>\n<h2>Quick revision</h2>\n<p>List the terms, dates or institutions candidates should remember.</p>` },
  { key: "quick-revision", name: "Quick revision notes", description: "Fast revision with concise facts and a question prompt.", html: `<p>Use this opening line to state the update and its exam relevance.</p>\n<h2>Remember these facts</h2>\n<ol>\n  <li><strong>Who?</strong> Name the people or institution involved.</li>\n  <li><strong>What?</strong> State the event or announcement.</li>\n  <li><strong>Where / when?</strong> Add the place and date, if relevant.</li>\n  <li><strong>Why?</strong> Note the key significance.</li>\n</ol>\n<h2>Try this</h2>\n<p><strong>Question:</strong> Write one practice question based on this update.</p>\n<p><strong>Answer:</strong> Add a concise answer with a short explanation.</p>\n<blockquote>Verify names, dates and figures against the cited source.</blockquote>` },
];

export function getCurrentAffairsTemplate(key: CurrentAffairsTemplate) {
  return CURRENT_AFFAIRS_TEMPLATES.find((template) => template.key === key) ?? CURRENT_AFFAIRS_TEMPLATES[0];
}
